language: cpp

sudo: required

services:
    - docker

os:
    - linux

before_install:
    - docker run --name PASO -d centos:centos7 /bin/sh -c "cd /root; bundle exec foreman start;"
    - docker ps -a
    - docker run centos:centos7 /bin/sh -c "cd /root; ls -la"

branches:
    only:
        - master


