-- CREATING TABLES --
CREATE TABLE SYSTEM_USER (
  USERNAME    VARCHAR(16) PRIMARY KEY,
  PASSWORD    VARCHAR(16) NOT NULL,
  FIRST_NAME  VARCHAR(32) NOT NULL,
  LAST_NAME   VARCHAR(32) NOT NULL,
  EMAIL       VARCHAR(64) NOT NULL,
  ROLE        VARCHAR(16) NOT NULL
);

CREATE TABLE COURSE (
  CODE        VARCHAR(8) PRIMARY KEY,
  NAME        VARCHAR(64) NOT NULL
);

CREATE TABLE LIST (
  ID_LIST     BIGSERIAL PRIMARY KEY,
  NAME        VARCHAR(32) NOT NULL,
  TYPE        CHAR(1) NOT NULL,
  PERMANENT   BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE ROOM (
  ROOM_UUID   UUID PRIMARY KEY,
  NAME        VARCHAR(64) NOT NULL,
  ROOM_NUMBER VARCHAR(8) NOT NULL
);

-- INSERTING INITIAL DATA --
INSERT INTO SYSTEM_USER(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ROLE)
  VALUES ('root', 'root', 'System', 'Administrator', 'root@paso.system', 'SUPER_USER');
