-- CREATING TABLES --
CREATE TABLE SYSTEM_USER (
    ID          BIGSERIAL PRIMARY KEY,
    USERNAME    VARCHAR(16) UNIQUE NOT NULL,
    PASSWORD    VARCHAR(16) NOT NULL,
    FIRST_NAME  VARCHAR(32) NOT NULL,
    LAST_NAME   VARCHAR(32) NOT NULL,
    EMAIL       VARCHAR(64) NOT NULL,
    ROLE        VARCHAR(16) NOT NULL
);

CREATE TABLE COURSE (
    ID          BIGSERIAL PRIMARY KEY,
    CODE        VARCHAR(8) UNIQUE NOT NULL,
    NAME        VARCHAR(64) NOT NULL
);

CREATE TABLE LIST (
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(32) NOT NULL,
    TYPE        CHAR(1) NOT NULL,
    PERMANENT   BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE ROOM (
    ID          BIGSERIAL PRIMARY KEY,
    ROOM_UUID   UUID UNIQUE NOT NULL,
    NAME        VARCHAR(64) NOT NULL,
    ROOM_NUMBER VARCHAR(8) UNIQUE NOT NULL
);

CREATE TABLE PERSON (
    ID          BIGSERIAL PRIMARY KEY,
    FIRST_NAME  VARCHAR(32) NOT NULL,
    LAST_NAME   VARCHAR(32) NOT NULL,
    EMAIL       VARCHAR(64) UNIQUE NOT NULL,
    RFID        VARCHAR(64) UNIQUE
);

CREATE TABLE STUDENT (
    ID              BIGINT PRIMARY KEY,
    INDEX_NUMBER    VARCHAR(9) UNIQUE NOT NULL,
    YEAR_OF_STUDY   INTEGER NOT NULL,
    FOREIGN KEY(ID) REFERENCES PERSON(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- INSERTING INITIAL DATA --
INSERT INTO SYSTEM_USER(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ROLE)
  VALUES ('root', 'root', 'System', 'Administrator', 'root@paso.system', 'SUPER_USER');
